---
openapi: 3.0.3
info:
  title: Sodoto
  version: 1.0.0
servers:
  - url: https://sodoto-api.onrender.com
paths:
  "/video_uploads":
    get:
      summary: index
      tags:
      - VideoUpload
      responses:
        '200':
          description: returns a list of video uploads
          content:
            application/json:
              schema:
                type: array
                items: {}
              example: []
